### ISSUE TITLE
Using SAM through QuPath script editor

### ISSUE THREAD

**Issue by jesusdpa1** [ksugar/qupath-extension-sam#10]
Hi, I was wondering if there is a way to access this extension from the script editor? I am planning on building a pipeline that would use SAM in the processing steps,

**Comment by ksugar** [comment]
Hi @jesusdpa1 , I wrote example scripts. Please try them.

https://github.com/ksugar/qupath-extension-sam/blob/a42b4f4ffcf295a4d34097d4ab2949ca86a79945/src/main/resources/scripts/bboxSAM.groovy#L1-L42

https://github.com/ksugar/qupath-extension-sam/blob/a42b4f4ffcf295a4d34097d4ab2949ca86a79945/src/main/resources/scripts/runAutomask.groovy#L1-L25

**Comment by jesusdpa1** [comment]
Thanks @ksugar! it works great! 

I am adding this for anyone looking into the topic later 

for the output type here is the information, just replace SAMOutput<.MULTI_SMALLEST> with the desire output type

```graddle
public enum SAMOutput {

    SINGLE_MASK, MULTI_ALL, MULTI_LARGEST, MULTI_SMALLEST, MULTI_BEST_QUALITY;

    @Override
    public String toString() {
        // Provide a more user-friendly name
        switch (this) {
            case SINGLE_MASK:
                return "Single mask";
            case MULTI_ALL:
                return "Multi-mask (all)";
            case MULTI_LARGEST:
                return "Multi-mask (largest)";
            case MULTI_SMALLEST:
                return "Multi-mask (smallest)";
            case MULTI_BEST_QUALITY:
                return "Multi-mask (best quality)";
        }
        throw new IllegalArgumentException("Unknown SAM output");
    }

```

**Comment by LPUoO** [comment]
Hi @ksugar,
What would be the correct argument to add in the SAMDetectionTask for 3D segmentation with or without custom Z limits?

![Image](https://github.com/user-attachments/assets/0843df49-9d27-4385-893a-f2eba4b47871)

Thanks!
