### ISSUE TITLE
Error installing extension on qupath

### ISSUE THREAD

**Issue by anesdo** [ksugar/qupath-extension-sam#13]
![image](https://github.com/ksugar/qupath-extension-sam/assets/72497341/da5b991b-d936-4cfe-82ec-6afb84a0863f)

**Comment by ksugar** [comment]
Hi @anesdo, thank you for reporting the issue.
In QuPath v0.5.0, you need to install [qupath-extension-sam-0.5.0.jar](https://github.com/ksugar/qupath-extension-sam/releases/download/v0.5.0/qupath-extension-sam-0.5.0.jar) instead of `v0.4.1`.

**Comment by anesdo** [comment]
![image](https://github.com/ksugar/qupath-extension-sam/assets/72497341/65fcce63-1783-42c2-9cd1-7dce34415563)

**Comment by ksugar** [comment]
Hi @anesdo, you need to set up the samapi server as well.

> Please note that you need to set up the server following the instructions in the link below.
> https://github.com/ksugar/samapi

Please let me know if you need further help.

**Comment by ksugar** [comment]
@anesdo how did you set up the server? Is it launched locally or remotely?
In the default setting, it is supposed to be available at http://localhost:8000/sam/.
The error in the screenshot indicates that the server is unavailable at http://localhost:8000/sam/.
It is helpful if you could share the terminal output from samapi.

```bash
INFO:     Started server process [21258]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```

**Comment by anesdo** [comment]
Problem solved! thank you!
