### ISSUE TITLE
Support SAM2

### ISSUE THREAD

**Issue by ksugar** [ksugar/qupath-extension-sam#19]
Add an option to support SAM2.
https://ai.meta.com/research/publications/sam-2-segment-anything-in-images-and-videos/
https://github.com/facebookresearch/segment-anything-2

**Comment by kyakabi** [comment]
Please excuse my ignorance, could you please give more detail on how to implement this new model? Thanks so much!

**Comment by ksugar** [comment]
Hi @kess-one, thank you for your question.
About the segmentation algorithm, I just need to add an option to the list for SAM2.
One of the powerful aspect of SAM2 is a tracking algorithm using a video data. I will need a little more work for that.
I am thinking to support the segmentation algorithm first, then move on to the tracking.

**Comment by ksugar** [comment]
v0.6.0 now supports SAM2. https://github.com/ksugar/qupath-extension-sam/pull/21
It requires the [samapi](https://github.com/ksugar/samapi) server `v0.5.0` or above.
