### ISSUE TITLE
Issue using the SAM Automask

### ISSUE THREAD

**Issue by PerfidAlbion** [ksugar/qupath-extension-sam#6]
Hello and thanks for the great work

I've followed the instruction to set up the server and it works fine with QuPath using SAM Prompt but when I want to try SAM auto mask I've got the following issue : 

INFO:     127.0.0.1:50717 - "POST /sam/automask/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
..
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. 

When I checked my install packages: 
Requirement already satisfied: torchvision in c:\users\jeanb\anaconda3\envs\samapi\lib\site-packages (0.15.2)
Requirement already satisfied: torch==2.0.1 in c:\users\jeanb\anaconda3\envs\samapi\lib\site-packages (from torchvision) (2.0.1+cu118)

Thanks for the help

**Comment by ksugar** [comment]
Hello @PerfidAlbion, thank you for reporting the issue and sorry for the late reply.

I have updated the installation steps of the samapi server to avoid this issue.
Please try the installation with the latest release `v0.3.1`.
https://github.com/ksugar/samapi
